#!/usr/bin/env python3
"""Rewrite Trellis-generated ZCode hook commands so they stop following the shell cwd.

ZCode expands ${ZCODE_PROJECT_DIR} (and injects the env var) anchored at the
persisted shell working directory, not the workspace root. Once a conversation
`cd`s into a subdirectory, every hook command generated by @mindfoldhq/trellis
as `python3 "${ZCODE_PROJECT_DIR}/.zcode/hooks/x.py"` resolves into
<subdir>/.zcode/hooks/ and fails; python exits 2 on a missing file, which ZCode
treats as a block. Root cause and verification matrix:
references/zcode-hook-pitfalls.md

This script rewrites those commands to anchor on the git repository root:
  R=$(git -C "${ZCODE_PROJECT_DIR}" rev-parse --show-toplevel 2>/dev/null || echo "${ZCODE_PROJECT_DIR}"); \
  export ZCODE_PROJECT_DIR="$R"; exec python3 "$R/.zcode/hooks/x.py"
Idempotent: anchored commands are left untouched, so re-running after a
`trellis update` that regenerates the fragile form simply re-fixes it.

Modes:
- positional PROJECT dirs: fix each project's .zcode/config.json
- --trellis-template: also patch the template inside the globally installed
  @mindfoldhq/trellis package, so future `trellis init` emits anchored commands.
  npm upgrade of the package reverts this; re-run the script afterwards.
- --check: report only, write nothing, exit 1 if any fragile command remains.

POSIX-only command shape (needs a shell with $()); Windows hosts are not
supported by this rewrite.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

ANCHORED_MARK = 'rev-parse --show-toplevel'
FRAGILE_RE = re.compile(
    r'^(?P<py>\S+)\s+"\$\{ZCODE_PROJECT_DIR\}/\.zcode/hooks/(?P<script>[\w.-]+)"\s*$'
)


def anchored_command(py: str, script: str) -> str:
    return (
        'R=$(git -C "${ZCODE_PROJECT_DIR}" rev-parse --show-toplevel 2>/dev/null '
        '|| echo "${ZCODE_PROJECT_DIR}"); '
        f'export ZCODE_PROJECT_DIR="$R"; exec {py} "$R/.zcode/hooks/{script}"'
    )


def iter_commands(cfg: dict):
    events = cfg.get("hooks", {}).get("events", {})
    for groups in events.values():
        for group in groups:
            for hook in group.get("hooks", []):
                if hook.get("type") == "command":
                    yield hook


def rewrite_config(path: Path, check_only: bool) -> tuple[int, int, int]:
    """Return (total, fixed, fragile_left) for one config file."""
    original = path.read_text(encoding="utf-8")
    cfg = json.loads(original)
    fixed = 0
    fragile_left = 0
    total = 0
    for hook in iter_commands(cfg):
        cmd = hook.get("command", "")
        total += 1
        if ANCHORED_MARK in cmd:
            continue
        match = FRAGILE_RE.match(cmd)
        if match:
            if not check_only:
                hook["command"] = anchored_command(match.group("py"), match.group("script"))
            fixed += 1
        else:
            fragile_left += 1
            print(f"  !! 无法识别且未锚定的命令，需人工确认: {cmd[:90]}")
    if fixed and not check_only:
        backup = path.with_name(path.name + ".bak-fix-zcode-hooks-" + datetime.now().strftime("%Y%m%d-%H%M%S"))
        shutil.copy2(path, backup)
        path.write_text(json.dumps(cfg, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"  已修复 {fixed} 条命令，备份: {backup.name}")
    return total, fixed, fragile_left


def trellis_template_path() -> Path | None:
    try:
        root = subprocess.run(["npm", "root", "-g"], capture_output=True, text=True, timeout=15)
    except (OSError, subprocess.SubprocessError):
        return None
    if root.returncode != 0:
        return None
    candidate = Path(root.stdout.strip()) / "@mindfoldhq" / "trellis" / "dist" / "templates" / "zcode" / "config.json"
    return candidate if candidate.is_file() else None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("projects", nargs="*", type=Path, help="项目根目录（含 .zcode/config.json）")
    parser.add_argument("--trellis-template", action="store_true",
                        help="同时修复全局安装的 @mindfoldhq/trellis 生成模板")
    parser.add_argument("--check", action="store_true", help="只报告不写入；存在脆弱命令时退出码 1")
    args = parser.parse_args()

    targets: list[tuple[str, Path]] = []
    if args.trellis_template:
        template = trellis_template_path()
        if template is None:
            print("!! 未找到全局 @mindfoldhq/trellis 模板（npm root -g 下无 dist/templates/zcode/config.json）")
            return 1
        targets.append(("trellis 模板", template))
    for project in args.projects:
        targets.append((str(project), project / ".zcode" / "config.json"))

    if not targets:
        parser.error("请至少提供项目目录或 --trellis-template")

    bad = 0
    for label, path in targets:
        if not path.is_file():
            print(f"[{label}] 无 {path}，跳过")
            continue
        print(f"[{label}] {path}")
        try:
            total, fixed, fragile_left = rewrite_config(path, args.check)
        except (json.JSONDecodeError, OSError) as exc:
            print(f"  !! 读取/解析失败: {exc}")
            bad += 1
            continue
        if total == 0:
            print("  （无 command 钩子）")
        if args.check and fixed:
            print(f"  发现 {fixed} 条脆弱命令（--check 未写入）")
            bad += 1
        if fragile_left:
            bad += 1
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
